<?xml version="1.0" encoding="utf-8"?><Database Name="SportShop" Class="SportShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=SportShop;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SportShopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Shoes" Member="Shoes">
    <Type Name="Shoe">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="shoeType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="model" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="inSale" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="photo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>